/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_facemodule_FaceRecognizer */

#ifndef _Included_org_facemodule_FaceRecognizer
#define _Included_org_facemodule_FaceRecognizer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_facemodule_FaceRecognizer
 * Method:    nativeCreateObject
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_org_facemodule_FaceRecognizer_nativeCreateObject
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_facemodule_FaceRecognizer
 * Method:    nativeStringArray
 * Signature: ([Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_facemodule_FaceRecognizer_nativeStringArray
  (JNIEnv *, jclass, jobjectArray);

/*
 * Class:     org_facemodule_FaceRecognizer
 * Method:    nativeDestroyObject
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_facemodule_FaceRecognizer_nativeDestroyObject
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_facemodule_FaceRecognizer
 * Method:    nativeTrain
 * Signature: (J[Ljava/lang/String;[I)V
 */
JNIEXPORT void JNICALL Java_org_facemodule_FaceRecognizer_nativeTrain
  (JNIEnv *, jclass, jlong, jobjectArray, jintArray);

/*
 * Class:     org_facemodule_FaceRecognizer
 * Method:    nativeUpdate
 * Signature: (J[Ljava/lang/String;[I)V
 */
JNIEXPORT void JNICALL Java_org_facemodule_FaceRecognizer_nativeUpdate
  (JNIEnv *, jclass, jlong, jobjectArray, jintArray);

/*
 * Class:     org_facemodule_FaceRecognizer
 * Method:    nativePredict
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_facemodule_FaceRecognizer_nativePredict
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
